export const SET_USER_INFO_BY_TOKEN = '[USER] SET USER INFO BY TOKEN';
export const LOGOUT_USER = '[USER] LOGOUT';

export const GET_STAKINGS = '[STAKING] GET LIST';
export const ADD_STAKING_POSITION = '[STAKING] ADD POSITION';

export const GET_CURRENCY_TRADING_REQUEST = '[TRADING] GET CURRENCY REQUEST';
export const GET_CURRENCY_TRADING_SUCCESS = '[TRADING] GET CURRENCY SUCCESS';
export const GET_CURRENCY_TRADING_FAILURE = '[TRADING] GET CURRENCY FAILURE';